<?php

return [

    'default_view_profile_content'=>[
        'p_name'=>'Archiwum wystaw',
        'type'=>'content',
        'suffix'=>'dfc',
        'icon'=>'/sections_icons/edukacja_dlugopis.svg',
        'color'=>[
            'rgb'=>'E3B5A4',
            'classname'=>'shilo-color',
            'bgrgb'=>'f5f5f5',
            'footbg'=>'f5f5f5'
        ]
    ],
    'default_view_profile_agenda'=>[
        'p_name'=>'Archiwum wydarzeń',
        'type'=>'agenda',
        'suffix'=>'dfa',
        'icon'=>'/sections_icons/edukacja_dlugopis.svg',
        'color'=>[
            'rgb'=>'E3B5A4',
            'classname'=>'shilo-color',
            'bgrgb'=>'f5f5f5',
            'footbg'=>'f5f5f5'
        ]
    ],
    'view_profile_config'=>[
        [
            'p_name'=>'O nas',
            'type'=>'content',
            'suffix'=>'on',
            'language'=>'pl',
            'icon'=>'/sections_icons/edukacja_dlugopis.svg',
            'color'=>[
                'rgb'=>'E3B5A4',
                'classname'=>'shilo-color',
                'bgrgb'=>'f5f5f5',
                'footbg'=>'f5f5f5'
            ]
        ],
        [
            'p_name'=>'Misja',
            'type'=>'content',
            'suffix'=>'mis',
            'language'=>'pl',
            'icon'=>'/sections_icons/edukacja_dlugopis.svg',
            'color'=>[
                'rgb'=>'E3B5A4',
                'classname'=>'shilo-color',
                'bgrgb'=>'f5f5f5',
                'footbg'=>'f5f5f5'
            ]
        ],
        [
            'p_name'=>'Zespół',
            'type'=>'content',
            'suffix'=>'zes',
            'language'=>'pl',
            'icon'=>'/sections_icons/edukacja_dlugopis.svg',
            'color'=>[
                'rgb'=>'E3B5A4',
                'classname'=>'shilo-color',
                'bgrgb'=>'f5f5f5',
                'footbg'=>'f5f5f5'
            ]
        ],

        [
            'p_name'=>'Spacer wirtualny',
            'type'=>'content',
            'suffix'=>'march',
            'language'=>'pl',
            'icon'=>'/sections_icons/edukacja_dlugopis.svg',
            'color'=>[
                'rgb'=>'E3B5A4',
                'classname'=>'shilo-color',
                'bgrgb'=>'f5f5f5',
                'footbg'=>'f5f5f5'
            ]
        ],

        [
            'p_name'=>'Wystawy',
            'type'=>'agenda',
            'suffix'=>'wys',
            'language'=>'pl',
            'icon'=>'/sections_icons/edukacja_dlugopis.svg',
            'color'=>[
                'rgb'=>'60BCB0',
                'classname'=>'puerto-rico-color',
                'bgrgb'=>'f5f5f5',
                'footbg'=>'f5f5f5'
            ]
        ],
        [
            'p_name'=>'Program',
            'type'=>'agenda',
            'suffix'=>'prg',
            'language'=>'pl',
            'icon'=>'/sections_icons/edukacja_dlugopis.svg',
            'color'=>[
                'rgb'=>'FF5B3B',
                'classname'=>'outrageous-orange-color',
                'bgrgb'=>'f5f5f5',
                'footbg'=>'f5f5f5'
            ]
        ],
        [
            'p_name'=>'Publikacje',
            'type'=>'content',
            'suffix'=>'pub',
            'language'=>'pl',
            'icon'=>'/sections_icons/edukacja_dlugopis.svg',
            'color'=>[
                'rgb'=>'F79D5C',
                'classname'=>'sandy-brown-color',
                'bgrgb'=>'f5f5f5',
                'footbg'=>'f5f5f5'
            ]
        ],
        [
            'p_name'=>'Edukacja',
            'type'=>'content',
            'suffix'=>'edu',
            'language'=>'pl',
            'icon'=>'/sections_icons/edukacja_dlugopis.svg',
            'color'=>[
                'rgb'=>'773344',
                'classname'=>'merlot-color',
                'bgrgb'=>'f5f5f5',
                'footbg'=>'f5f5f5'
            ]
        ],
        [
            'p_name'=>'Historia Mówiona',
            'type'=>'content',
            'suffix'=>'ahm',
            'language'=>'pl',
            'icon'=>'/sections_icons/edukacja_dlugopis.svg',
            'color'=>[
                'rgb'=>'2EA7FF',
                'classname'=>'dodger-blue-color',
                'bgrgb'=>'D6E1EE',
                'footbg'=>'D6E1EE'
            ]
        ],
        [
            'p_name'=>'Multimedia',
            'type'=>'content',
            'suffix'=>'mm',
            'language'=>'pl',
            'icon'=>'/sections_icons/edukacja_dlugopis.svg',
            'color'=>[
                'rgb'=>'018187',
                'classname'=>'teal-color',
                'bgrgb'=>'f5f5f5',
                'footbg'=>'EDEDED'
            ]
        ],
        [
            'p_name'=>'Projekty specjalne',
            'type'=>'content',
            'suffix'=>'prs',
            'language'=>'pl',
            'icon'=>'/sections_icons/edukacja_dlugopis.svg',
            'color'=>[
                'rgb'=>'FFBD21',
                'classname'=>'sunglow-color',
                'bgrgb'=>'FCF5E6',
                'footbg'=>'FCF5E6'
            ]
        ],

        ///////////////////////////////////////////////////////////////////

        [
            'p_name'=>'O nas',
            'type'=>'content',
            'suffix'=>'ab',
            'language'=>'en',
            'icon'=>'/sections_icons/edukacja_dlugopis.svg',
            'color'=>[
                'rgb'=>'E3B5A4',
                'classname'=>'shilo-color',
                'bgrgb'=>'f5f5f5',
                'footbg'=>'f5f5f5'
            ]
        ],
        [
            'p_name'=>'Misja',
            'type'=>'content',
            'suffix'=>'miss',
            'language'=>'en',
            'icon'=>'/sections_icons/edukacja_dlugopis.svg',
            'color'=>[
                'rgb'=>'E3B5A4',
                'classname'=>'shilo-color',
                'bgrgb'=>'f5f5f5',
                'footbg'=>'f5f5f5'
            ]
        ],
        [
            'p_name'=>'Zespół',
            'type'=>'content',
            'suffix'=>'team',
            'language'=>'en',
            'icon'=>'/sections_icons/edukacja_dlugopis.svg',
            'color'=>[
                'rgb'=>'E3B5A4',
                'classname'=>'shilo-color',
                'bgrgb'=>'f5f5f5',
                'footbg'=>'f5f5f5'
            ]
        ],

        [
            'p_name'=>'Zespół',
            'type'=>'content',
            'suffix'=>'march',
            'language'=>'en',
            'icon'=>'/sections_icons/edukacja_dlugopis.svg',
            'color'=>[
                'rgb'=>'E3B5A4',
                'classname'=>'shilo-color',
                'bgrgb'=>'f5f5f5',
                'footbg'=>'f5f5f5'
            ]
        ],

        [
            'p_name'=>'Wystawy',
            'type'=>'agenda',
            'suffix'=>'exhi',
            'language'=>'en',
            'icon'=>'/sections_icons/edukacja_dlugopis.svg',
            'color'=>[
                'rgb'=>'60BCB0',
                'classname'=>'puerto-rico-color',
                'bgrgb'=>'f5f5f5',
                'footbg'=>'f5f5f5'
            ]
        ],
        [
            'p_name'=>'Program',
            'type'=>'agenda',
            'suffix'=>'prog',
            'language'=>'en',
            'icon'=>'/sections_icons/edukacja_dlugopis.svg',
            'color'=>[
                'rgb'=>'FF5B3B',
                'classname'=>'outrageous-orange-color',
                'bgrgb'=>'f5f5f5',
                'footbg'=>'f5f5f5'
            ]
        ],
        [
            'p_name'=>'Publikacje',
            'type'=>'content',
            'suffix'=>'publish',
            'language'=>'en',
            'icon'=>'/sections_icons/edukacja_dlugopis.svg',
            'color'=>[
                'rgb'=>'F79D5C',
                'classname'=>'sandy-brown-color',
                'bgrgb'=>'f5f5f5',
                'footbg'=>'f5f5f5'
            ]
        ],
        [
            'p_name'=>'Edukacja',
            'type'=>'content',
            'suffix'=>'educ',
            'language'=>'en',
            'icon'=>'/sections_icons/edukacja_dlugopis.svg',
            'color'=>[
                'rgb'=>'773344',
                'classname'=>'merlot-color',
                'bgrgb'=>'f5f5f5',
                'footbg'=>'f5f5f5'
            ]
        ],
        [
            'p_name'=>'Historia Mówiona',
            'type'=>'content',
            'suffix'=>'ahmen',
            'language'=>'en',
            'icon'=>'/sections_icons/edukacja_dlugopis.svg',
            'color'=>[
                'rgb'=>'2EA7FF',
                'classname'=>'dodger-blue-color',
                'bgrgb'=>'D6E1EE',
                'footbg'=>'D6E1EE'
            ]
        ],
        [
            'p_name'=>'Multimedia',
            'type'=>'content',
            'suffix'=>'mmen',
            'language'=>'en',
            'icon'=>'/sections_icons/edukacja_dlugopis.svg',
            'color'=>[
                'rgb'=>'018187',
                'classname'=>'teal-color',
                'bgrgb'=>'f5f5f5',
                'footbg'=>'EDEDED'
            ]
        ],
        [
            'p_name'=>'Projekty specjalne',
            'type'=>'content',
            'suffix'=>'prsen',
            'language'=>'en',
            'icon'=>'/sections_icons/edukacja_dlugopis.svg',
            'color'=>[
                'rgb'=>'FFBD21',
                'classname'=>'sunglow-color',
                'bgrgb'=>'FCF5E6',
                'footbg'=>'FCF5E6'
            ]
        ]

    ],
    'view_profile_config_publication'=>[

                [
                    'p_name'=>'Profil widoku',
                    'type'=>'publication',
                    'lang'=>2,
                    'suffix'=>'oglopl',
                    'icon'=>'/sections_icons/edukacja_dlugopis.svg',
                    'color'=>[
                        'rgb'=>'E3B5A4',
                        'classname'=>'shilo-color',
                        'bgrgb'=>'f5f5f5',
                        'footbg'=>'f5f5f5'
                    ]
                ],
                [
                    'p_name'=>'Profil widoku',
                    'type'=>'publication',
                    'lang'=>1,
                    'suffix'=>'ogloen',
                    'icon'=>'/sections_icons/edukacja_dlugopis.svg',
                    'color'=>[
                        'rgb'=>'E3B5A4',
                        'classname'=>'shilo-color',
                        'bgrgb'=>'f5f5f5',
                        'footbg'=>'f5f5f5'
                    ]

                ]

    ]
];